# Generated by Django 3.0.8 on 2020-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200806_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('checking', 'Checking'), ('error', 'Error'), ('ok', 'OK')], default='checking', max_length=10),
        ),
    ]
