# Generated by Django 3.0.8 on 2020-08-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_service_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='task',
        ),
    ]
