# Generated by Django 3.2.12 on 2022-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220411_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('checking', 'Checking'), ('error', 'Error'), ('unavailable', 'Unavailable'), ('ok', 'OK')], default='checking', max_length=20),
        ),
    ]
