# Generated by Django 3.2.12 on 2022-04-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_service_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='is_activate',
            field=models.BooleanField(default=False, help_text='Service status'),
        ),
    ]
