version: "3.5"

services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - backend

  app:
    container_name: heathchecker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - backend

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A healthchecker worker --loglevel=info -B
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
