# Generated by Django 3.2.12 on 2022-04-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redis',
            new_name='System',
        ),
    ]
