# Generated by Django 3.2.12 on 2022-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_redis_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'System', 'verbose_name_plural': 'systems'},
        ),
    ]
