# Generated by Django 3.2.12 on 2022-04-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_system_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
