# Generated by Django 3.2.12 on 2022-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_system_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
