# Generated by Django 3.2.12 on 2022-04-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_system_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
