# Generated by Django 3.2.12 on 2022-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_system_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='service_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
